version: "3.8"
services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: docker-dev-env-db
      MYSQL_PASSWORD: docker-dev-env-db-password
      MYSQL_ROOT_PASSWORD: docker-dev-env-db-root-password
      MYSQL_USER: docker-dev-env-user
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:1.19-alpine
    environment:
      VIRTUAL_HOST: testing.local
    restart: "no"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public:ro

  php:
    build:
      target: dev
    restart: "no"
    depends_on:
      - composer
      - db
    volumes:
      - ./:/app
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini

  node:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run watch"

  composer:
    image: composer:2
    working_dir: /app
    environment:
      SSH_AUTH_SOCK: /ssh-auth.sock
    volumes:
      - ./:/app
      - "$SSH_AUTH_SOCK:/ssh-auth.sock"
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: composer install --ignore-platform-reqs --no-scripts

volumes:
  db-data:
